Create [운영체제] 운영체제와 컴퓨터 구조.md
Shortudy-10th/tech-for-developer pull request #139
Opened 2023-08-20 13:26 UTC by watty-exclamationMark

[운영체제] 운체랑 컴구
늦어서 죄송...

2023-08-20 13:47 UTC, sikutisa approved these changes

2023-08-20 14:37 UTC, seongeun42 approved these changes
멋져요💕

2023-08-20 22:49 UTC, zini9188 approved these changes
👍👍

2023-08-21 04:40 UTC, Jihn0118 requested changes
77번 라인
vs interrupt 

확인 부탁 드립니다~

2023-08-21 04:58 UTC, Jihn0118 approved these changes
👍👍

2023-08-21 05:03 UTC, aeroej approved these changes
LGTM

2023-08-25 04:11 UTC, LireEruel approved these changes

2023-08-29 12:59 UTC, merged