docs: add [자료구조] 트리.md
Shortudy-10th/tech-for-developer pull request #72
Opened 2023-08-10 13:25 UTC by zini9188

2023-08-10 13:41 UTC, sikutisa requested changes

2023-08-10 13:41 UTC, sikutisa commented on [자료구조] 트리.md
> +   - 이로인해 4번 조건이 위배되는 케이스가 등장할 수 있다.
디스커션에서의 RB트리 조건 나열 순서와 정리 파일에서의 조건 순서가 달라서 맥락이 맞지 않는 문장이 된 것 같습니다.
**4번 조건**을 **Red 노드의 자식 노드들은 전부 Black이어야 하는 조건**으로 변경해주세요.

2023-08-10 13:41 UTC, sikutisa commented on [자료구조] 트리.md
> +* 위에서 노드 2는 2개의 NIL을 가지고, 이 NIL을 검은색 노드라고 생각한다면 조건 3을 해치지 않게 된다.
81라인과 동일한 이유입니다.
**조건 3**을 **모든 Leaf 노드는 Black이어야 하는 조건**으로 변경해주세요.

2023-08-10 14:54 UTC, seongeun42 requested changes

2023-08-10 14:54 UTC, seongeun42 commented on [자료구조] 트리.md
> +- 어떤 값에 대해서도 같은 시간에 결과를 가질 수 있는 균일성을 가진다.
같은 시간에 어떤 결과를 가지는지 설명이 필요해 보입니다.

2023-08-10 14:54 UTC, seongeun42 commented on [자료구조] 트리.md
> +의 시간 복잡도로 삽입, 삭제, 검색을 할 수 있다. 레드-블랙 트리는 자식 노드가 존재하지 않는 경우 NIL이라는 특수 노드를 둔다. 즉, 모든 Leaf 노드는 NIL이다.`
58-59 이 부분 레드-블랙 트리 탐색 시간복잡도 식이 날아갔습니다.

2023-08-11 00:04 UTC, watty-exclamationMark approved these changes
오잉. 이거 Approve 하면 되나요?

2023-08-11 04:26 UTC, sikutisa approved these changes

2023-08-11 08:46 UTC, LireEruel reviewed
조아용!!

2023-08-11 10:03 UTC, seongeun42 approved these changes

2023-08-11 11:32 UTC, merged