doc: add [자료구조] 그래프.md
Shortudy-10th/tech-for-developer pull request #93
Opened 2023-08-12 06:32 UTC by sikutisa

2023-08-12 09:09 UTC, seongeun42 requested changes
꼬리 질문 </details> <details> 이 사이에 <br>로 공백 하나씩 넣어주면 더 보기 편할 것 같습니다.

2023-08-12 09:09 UTC, seongeun42 commented on [자료구조] 그래프.md
> +       - 헤드포인터: 연결 리스트의 맨 처음 노드를 가리키는 포인터
헤드포인터 추가 설명 부분이 윗줄이랑 연결돼서 보여요.

2023-08-12 14:08 UTC, sikutisa commented on [자료구조] 그래프.md
> +       - 헤드포인터: 연결 리스트의 맨 처음 노드를 가리키는 포인터
해당 부분 수정했습니다

2023-08-12 14:09 UTC, sikutisa commented
> 꼬리 질문 /details 태그랑 details 태그 이 사이에 로 공백 하나씩 넣어주면 더 보기 편할 것 같습니다.

제가 어떤 의미신지 잘 이해가 안 돼서 모든 details 태그와 /details 태그 앞뒤로 개행 하나씩 넣었습니다.

2023-08-12 14:10 UTC, watty-exclamationMark approved these changes

2023-08-12 14:10 UTC, watty-exclamationMark commented on [자료구조] 그래프.md
> +* 적합하지 않은 경우가 너 많다.
오타있어용
너 많다 -> 너무 많다

2023-08-12 14:12 UTC, sikutisa commented on [자료구조] 그래프.md
> +* 적합하지 않은 경우가 너 많다.
수정했습니다.

2023-08-12 14:19 UTC, watty-exclamationMark approved these changes
굿굿!

2023-08-12 19:16 UTC, seongeun42 commented
> > 꼬리 질문 /details 태그랑 details 태그 이 사이에 로 공백 하나씩 넣어주면 더 보기 편할 것 같습니다.
> 
> 제가 어떤 의미신지 잘 이해가 안 돼서 모든 details 태그와 /details 태그 앞뒤로 개행 하나씩 넣었습니다.


아, <br> 태그 넣어달라는 말이었습니다. 개행 맞아요.

2023-08-12 19:17 UTC, seongeun42 approved these changes

2023-08-13 01:21 UTC, zini9188 approved these changes

2023-08-13 01:36 UTC, sikutisa commented on [자료구조] 그래프.md
> +* 적합하지 않은 경우가 너 많다.
25c52403a553056ceac4506442bf5cc64d74c7c2 에서 해결된 내용인 것 같습니다.

2023-08-13 02:22 UTC, Jihn0118 reviewed
확인했습니다 👍

2023-08-13 02:23 UTC, Jihn0118 approved these changes

2023-08-14 05:26 UTC, aeroej approved these changes
굿굿!

2023-08-15 02:54 UTC, LireEruel approved these changes

2023-08-15 12:17 UTC, merged